apiVersion: v1
kind: ConfigMap
metadata: 
  name: catalogue
  namespace: roboshop 
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"


---
apiVersion: apps/v1
kind: Deployment
metadata:   
  name: catalogue
  labels:
    component: catalogue
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: catalogue
        project: roboshop
        tier: backend
    spec:
      containers:
        - name: catalogue
          image: abhishekyalla/catalogue:v1
          imagePullPolicy: Always
          envFrom:
           - configMapRef:
              name: catalogue
          ports:
            - containerPort: 8080
          readinessProbe:
              httpGet:
              path: /health
              port: 8080
              failureThreshold: 1
              periodSeconds: 15
          livenessProbe:
              httpGet:
              path: /health
              port: 8080
              failureThreshold: 1
              periodSeconds: 15

---

apiVersion: v1 
kind: Service
metadata:
  name: catalogue
  namespace: roboshop 
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: backend
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080

    