apiVersion: v1 
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user
  namespace: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      componenet: user
      project: roboshop
      tier: backend
  template:
    metadata:
     labels:
      componenet: user
      project: roboshop
      tier: backend
    spec:
      containers:
        - name: user
          image: abhishekyalla/user:v1
          imagePullPolicy: Always
          ports:
           
             containerPort: 8080
          envFrom:
            - configMapRef:
              name: user
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              failureThreshold: 1
              periodSeconds: 15

---
apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: roboshop
spec: 
  selector: 
    component: user
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port 
      